version: '3.8'

services:
  mypostgres:
    image: postgres:17
    container_name: mypostgres
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_PASSWORD: 16052021
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bingo_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      mypostgres:
        condition: service_healthy
    env_file:
      - .env.test
    ports:
      - "5000:5000"