name: Pipeline Automatizado

on:
  push:
    branches:
      - main

jobs:
  CI-ContinuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          echo 'DATABASE_URL="postgresql://postgres:16052021@mypostgres:5432/bingo_database_tests"' > .env.test

      - name: Run tests
        run: docker compose -f docker-compose-test.yml run backend npm run test

  CD-DeployToRender:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: CI-ContinuousIntegration 
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
