name: Pipeline Automatizado
on:
  push:
    branches:
      - main
jobs:
  CI-ContinuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          echo 'DATABASE_URL="postgresql://postgres:16052021@mypostgres:5432/bingo_database_tests"' > .env.test

      - name: Run tests
        run: docker compose -f docker-compose-test.yml run backend npm run test